### PR TITLE
Clean Ros2RoboticManipulationTemplate

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## What does this PR do?

Update `RoboticManipulationTemplate` to use prefabs, textures, and materials from other Gems instead of the own copies. Remove the copies. 

## How was this PR tested?

The template was built and run with no issues against o3de `6f814273e8`

### CODE REVIEW

**Review by arturkamieniecki — APPROVED** [review]

**Review by pawelbudziszewski — APPROVED** [review]
Good job!

**Review by adamdbrw — APPROVED** [review]

**Comment by jhanca-robotecai** [comment]
I force-pushed the PR after changing a few letters in the commit's description to change anyhow HEAD of the branch as it is not detected by AR....

**Comment by Ulrick28** [comment]
@amzn-mike Are you looking at a bypass for this as well?

**Comment by amzn-changml** [comment]
> @amzn-mike Are you looking at a bypass for this as well?

I'm taking a look at this

**Pull request merged**
