### PR TITLE
Add 2D Lidar to RosBot

### PR DESCRIPTION
**Pull request by michalpelka**
I've changed the structure with rosbot prebabs, now basic Rosbot prefab is overridden with new sensor configuration:

Screenshot from 2023-04-12 13-28-26

This change is targeted to development and contains:
- https://github.com/o3de/o3de-extras/pull/243
- https://github.com/o3de/o3de-extras/pull/255

CheckList:
- [ ] Rebase on top of https://github.com/o3de/o3de-extras/pull/255 after merge of https://github.com/o3de/o3de-extras/pull/255

### CODE REVIEW

**Comment by pawelbudziszewski** [comment]
The radar behaves incorrectly if tilted. 
I rotated it ~20deg around X axis:
Screenshot from 2023-04-13 13-38-31

Result:
https://user-images.githubusercontent.com/31925544/231750644-019f1fa0-4f01-470c-ab26-e3e630a09d27.mp4

**Comment by pawelbudziszewski** [comment]
It seems, that the problem originates from the 3D lidar #268

**Comment by adamdbrw** [comment]
@michalpelka is this something we also want in stabilization? If so, I would first merge there, then make a back-merge to development with a bunch of other PRs.

**Comment by michalpelka** [comment]
It should go to stabilization first.

**Comment by adamdbrw** [comment]
@pawelbudziszewski @michalpelka this can now be rebased since the #247 is merged, please do so.

**Comment by michalpelka** [comment]
Replaced by https://github.com/o3de/o3de-extras/pull/298

**Pull request closed without merging**
