### PR TITLE
 [ROS2] Remove deprecated documentation 

### LINKED ISSUE #730: [ROS2] Deprecated documentation
**Describe the bug**

The file: https://github.com/o3de/o3de-extras/blob/development/Gems/ROS2/docs/guides/ros2-gem.md is deprecated and should be removed, instead we have https://www.docs.o3de.org/docs/user-guide/interactivity/robotics/project-configuration/ .

**Assets required**
N/A

**Steps to reproduce**
N/A

**Expected behavior**
Single place to put documentation

**Actual behavior**
Two de synchronized documentation documents

**Screenshots/Video**
N/A

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) and [o3de/o3de-extras](https://github.com/o3de/o3de-extras) repositories**
[6641901](https://github.com/o3de/o3de-extras/commit/6641901f830a70ad0480a3039e0870784e21cfe1)
O3DE repo commit is not required

**Desktop/Device (please complete the following information):**
Any

### PR DESCRIPTION
**Pull request by Fireronin**
## What does this PR do?

Resolves #730 

## How was this PR tested?
 
N/A

### CODE REVIEW

**Comment by adamdbrw** [comment]
Good change - but there is more of deprecated content, such as 
https://github.com/o3de/o3de-extras/blob/development/Gems/ROS2/docs/guides/development_in_clion.md
pointing to old inactive fork. Similarly, there are bad links in the third md.

**Comment by michalpelka** [comment]
Please add DCO to all your commits @Fireronin

**Comment by Fireronin** [comment]
> Please add DCO to all your commits @Fireronin

Done

**Comment by jhanca-robotecai** [comment]
Agree with @adamdbrw 
Moreover, I see no reason for this one: https://github.com/o3de/o3de-extras/blob/development/Gems/ROS2/docs/guides/pr_publishing.md as there is a [guide](https://www.docs.o3de.org/docs/contributing/) how to contribute to O3DE

**Review by jhanca-robotecai — CHANGES_REQUESTED** [review]
Please see my comment for details. Marking as `request changes` for convenience.

**Review by jhanca-robotecai — CHANGES_REQUESTED** [review]
Diagram `diagram_ros2_gem` is referenced only in `ros2-gem.md` you removed. These files (both render and source) should be removed as well.

Moreover, the clean-up should be complete. Please double-check if files in `docs/design` folder are still needed and remove if necessary. Thanks!

**Review by michalpelka — APPROVED** [review]

**Comment by michalpelka** [comment]
@Fireronin, please fix DCO.

**Review by jhanca-robotecai — APPROVED** [review]
LGTM

**Pull request merged**
