### PR TITLE
Proteus Robot Gem

### PR DESCRIPTION
**Pull request by michalpelka**
- [x] Accept the name of the gem
- [x] List of contributors/authors
- [x] Add icon
- [x] Adjust namespaces for fleet usecase (now it is the same like in RosBot).

### CODE REVIEW

**Review by pawelbudziszewski — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
LGTM 👍

**Comment by hultonha** [comment]
Build started - https://jenkins.build.o3de.org/view/Projects/job/o3de-extras/view/change-requests/job/PR-173/1/

**Comment by adamdbrw** [comment]
This PR contributes to #181

**Comment by michalpelka** [comment]
@hultonha what is you recommendation on converting it to asset gem?

**Review by lemonade-dm — APPROVED** [review]

**Comment by hultonha** [comment]
> @hultonha what are your recommendations on converting it to asset gem?

Hey @michalpelka, I see this was done with the Warehouse Gem, I wonder is it possible in this case too? Just feels like we don't need all the component cruft in this case. What do you think? Thanks!

**Comment by michalpelka** [comment]
@hultonha I can do that, but I think that we will add in future some robot-specific component (e.g. for lift capabilities).

**Comment by hultonha** [comment]
> @hultonha I can do that, but I think that we will add in future some robot-specific component (e.g. lighting effects).

I see, in that case it's totally fine, it was only if this was exclusively assets. Thanks for the extra info :+1:

**Comment by hultonha** [comment]
Just started a new build here - https://jenkins.build.o3de.org/view/Projects/job/o3de-extras/view/change-requests/job/PR-173/2/

**Review by spham-amzn — APPROVED** [review]

**Review by shawstar — COMMENTED** [review]
Looks good.

**Pull request merged**
