### PR TITLE
Made ROS2Frame required for ROS2Odometry to prevent possible crash on run

### PR DESCRIPTION
**Pull request by MateuszWasilewski**
Added ROS2Frame as required service for ROS2OdometrySensor.
Added Assert after getting component to prevent segfault without indication to cause.
Fix for Issue 196

### CODE REVIEW

**Comment by michalpelka** [comment]
Solves #196 .

**Review by michalpelka — APPROVED** [review]
LGTM

**Review by hultonha — APPROVED** [review]
LGTM! 🙂

**Comment by michalpelka** [comment]
I can see that failed build in the same way #194 and #197 with asset processor test, and with finishing Editor in another.

**Comment by hultonha** [comment]
> I can see that failed build in the same way #194 and #197 with asset processor test, and with finishing Editor in another.

Hi @michalpelka, I believe this should be resolved now. If you can please update/rebase these branches and then I'll start another build for each 👍

**Review by lumberyard-employee-dm — APPROVED** [review]

**Pull request merged**
