### PR TITLE
Remove unused data from Ros2RoboticManipulationTemplate 

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
## What does this PR do?

Remove unused meshes and prefabs from [Ros2RoboticManipulationTemplate](https://github.com/o3de/o3de-extras/tree/development/Templates/Ros2RoboticManipulationTemplate)

## How was this PR tested?

The template was built and run.

### CODE REVIEW

**Review by pawelbudziszewski — COMMENTED** [review]
Please remove following files from `template.json`:

- 1K_Wall_Paint_Basecolor.jpg
- Grass_001_Roughness.jpg

**Comment by jhanca-robotecai** [comment]
> Please remove following files from `template.json`:
> 
> * 1K_Wall_Paint_Basecolor.jpg
> * Grass_001_Roughness.jpg

Good catch, thank you for checking my changes carefully

**Review by pawelbudziszewski — APPROVED** [review]

**Review by arturkamieniecki — APPROVED** [review]
Looks fine and works

**Comment by michalpelka** [comment]
Need manual rebase

**Review by michalpelka — APPROVED** [review]

**Pull request merged**
