### PR TITLE
Multiplayer Template Fix

### PR DESCRIPTION
**Pull request by AMZN-Gene**
Fixes Multiplayer Template to work with latest O3DE development branch

Started from scratch by generating a project using DefaultProject template instead of attempting to salvage the old Multiplayer Template 
Copied useful MultiplayerSample (MPS) components and assets
Does _not_ include MPS jump pads or environment

This PR does _not_ update the o3de-extra repo.json file and so does not make the new multiplayer template available for zipped download via project manager. Users will need to git pull this template by hand in order to use it to start their own project.

No particle fx are included due to MPS using PopcornFx (3rd party particle system)

Files of Interest
- Moved all assets under a root "Assets" folder to declutter the root directory
- https://github.com/o3de/o3de-extras/pull/735/files#diff-0f67834deac3297ebfcc9ccf8e76a85021491b2396b788b7bbccfb75a5251ac5
- https://github.com/o3de/o3de-extras/pull/735/files#diff-d63860ebf8ce96f62b2fb988513c6c2648ce759facfa281fefe20ef592d1fda6
- https://github.com/o3de/o3de-extras/pull/735/files#diff-65d1610f4c40b639e4bc6f958c8d5a08b7aa53871bf0c73c47a6c124ada4ebd7
    - I wanted to #include an AutoGen'd file inside the GameModule.cpp, in order to register the multiplayer component but the AutoGen folders are made private to the static modules. Work around adding the auto-gen folders by hand:
```
   INCLUDE_DIRECTORIES
        PRIVATE
            ${CMAKE_CURRENT_BINARY_DIR}/Azcg/Generated/${gem_name}.Client.Static # Used so Module.cpp can include AutoGen/AutoComponentTypes.h
```
- Multiplayer components and autogen.xml are direct copies from Multiplayer Sample

Assets from Multiplayer Sample
- Mixamo Y-Bot character, animations, and materials
- Laser gun
- HUD Reticle (Note, the reticle script for pulsing when being hit, or hitting another player was not brought over) 
   - Not included: https://github.com/o3de/o3de-multiplayersample/blob/development/scriptcanvas/DamageFlash.scriptcanvas
   - Not included: https://github.com/o3de/o3de-multiplayersample/blob/development/scriptcanvas/ReticleEffects.scriptcanvas
  

Fixes https://github.com/o3de/o3de-extras/issues/315
Fixes https://github.com/o3de/o3de-extras/issues/332
Fixes https://github.com/o3de/o3de-extras/issues/684
Fixes https://github.com/o3de/o3de-extras/issues/696

## How was this PR tested?
Generate a new project using the new Multiplayer template. 
`.\scripts\o3de.bat create-project -pp d:\MyGame -tn Multiplayer `
Running editor and CTRL+G to see network player spawn, run around, and shoot boxes.
Running serverlauncher and connecting 2 clients to see network players.

### CODE REVIEW

**Comment by GaianHelmers** [comment]
With this fix, my PR can be closed: https://github.com/o3de/o3de-extras/pull/701

**Comment by jhanca-robotecai** [comment]
I see you target the `development` branch with this PR. Should we consider a cherry-pick to the `stabilization/2409` as well?

**Review by gadams3 — APPROVED** [review]

**Comment by GaianHelmers** [comment]
I was curious to know.

If you put a random new script graph into the level with say a print node, then run it. Does the server sync correctly with the client viewport?

Then if you exit playmode, change the scriptgraph, then re-run playmode, does it still successfully launch?
The last big issue I was having with MP was the inability for changes in my editor to propagate to the server, which would then just leave me connected to a blank level.

Not sure if this is necessary to the scope of this PR, but I feel it would be worth identifying if it's still an issue.

**Comment by spham-amzn** [comment]
Don't forget to upload the template to the releases and update the repo.json accordingly

**Review by spham-amzn — APPROVED** [review]

**Pull request merged**
