### PR TITLE
Fixed project creation from ROS2RoboticManipulationTemplate

### PR DESCRIPTION
**Pull request by lewandowskikacper**
Removed file `o3de-extras/Templates/Ros2RoboticManipulationTemplate/Template/user/Registry/ViewBookmarks/RoboticPalletization_1691268770764352914.setreg` from template.json, as it doesn't exist.
Fixes:  https://github.com/o3de/o3de-extras/issues/495

### CODE REVIEW

**Comment by adamdbrw** [comment]
Nice work @lewandowskikacper. Let me know when you remove draft status.

**Review by adamdbrw — APPROVED** [review]

**Comment by michalpelka** [comment]
Add this file to repo since it is a default view point
If this file is missing from repo : https://gist.github.com/michalpelka/c09827ac0ee60a89b6b579ac9c3f1089

**Comment by lewandowskikacper** [comment]
> Add this file to repo since it is a default view point for the level RoboticPalletization.
> If this file is missing from repo here is a copy : https://gist.github.com/michalpelka/c09827ac0ee60a89b6b579ac9c3f1089

Yes, that of course makes more sense.
`user` is  ignored by git, so the file was not present.

I restored it, based on your snippet, and changed the starting position a bit

previous:
Screenshot from 2023-09-07 14-49-18


current:
Screenshot from 2023-09-07 14-48-32

**Review by michalpelka — APPROVED** [review]
Great Change!

**Pull request merged**
