### PR TITLE
Update ROS 2 versions and gems versions in project templates.

### PR DESCRIPTION
**Pull request by michalpelka**
## What does this PR do?

This PR updates ROS2 gem version and other gem version to release candidate from o3de(-extras)/stabilization_2409.
It addresses issue https://github.com/o3de/o3de/issues/18071 but with respect to project templates.

## How was this PR tested?

Build projects and run in project-centric approach using GUI.

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
I cherry-picked your changes into: https://github.com/o3de/o3de-extras/pull/723
I think it makes sense to include all changes in one PR, let me know if you disagree.

**Comment by michalpelka** [comment]
It is great idea to cherry-pick it to development, let me retarget it

**Review by spham-amzn — APPROVED** [review]
thank you!

**Comment by spham-amzn** [comment]
I am updating the stabilization [PR](https://github.com/o3de/o3de-extras/pull/718) and will incorporate this fix in there as well. Once its merged in, i'll cherry pick it back into development.

**Comment by spham-amzn** [comment]
You can discard this PR, based on our previous discussions, we are leaving the ROS2 gem at version 3.1.0 [PR](https://github.com/o3de/o3de-extras/pull/727) and the development version was bumped to 3.2.0 [PR](https://github.com/o3de/o3de-extras/pull/728)

**Comment by jhanca-robotecai** [comment]
As mentioned earlier, it was agreed to keep 3.1.0 for the release and 3.2.0 for the development. The correct versions are already set or on the way to be set (#723 ). I am closing this PR.

**Pull request closed without merging**
