### PR TITLE
Imported updated Husarion model with LiDAR.

### PR DESCRIPTION
**Pull request by michalpelka**
Imported Velodyne equipped description from https://github.com/husarion/rosbot_xl_ros/tree/velodyne-realsense-model. 
Screenshot from 2023-02-13 09-25-01

Signed-off-by: Michał Pełka <michal.pelka@robotec.ai>

### CODE REVIEW

**Review by adamdbrw — APPROVED** [review]

**Review by hultonha — APPROVED** [review]
Nice! Thanks for including the image in the description too, looks cool! 🙂

**Comment by hultonha** [comment]
Build started here - https://jenkins.build.o3de.org/view/Projects/job/o3de-extras/view/change-requests/job/PR-165/1/

**Comment by michalpelka** [comment]
rebased, but I would not merge it now, since it has a collider. I would wait for #195 merged.

**Comment by michalpelka** [comment]
It is not affected by the split of colliders in PhysX Gem. It added only EditorShapeCollider (collider).

**Comment by michalpelka** [comment]
Rebased manually, one more time.

**Review by spham-amzn — APPROVED** [review]

**Pull request merged**
